In [1]:
import numpy as np
from numpy import linalg as LA

__Definition: Characteristic Polynomial__

If $A$ is a square matrix, the __characteristic polynomial__ of A is defined by, 

$$
p(\lambda) = det(A - \lambda I)
$$

__Definition: Eigenvalue and Eigenvector__

If $p$ is the characteristic polynomial of a square matrix $A$, the zeros of $p$ are __eigenvalues__, or characteristic values, of the matrix $A$. If $\lambda$ is an eigenvalue of $A$ and $\bold{x} \ne \bold{0}$ satisfies $(A - \lambda I) \bold{x} = \bold{0}$, then $\bold{x}$ is an __eigenvector__, or characteristic vector, of $A$ corresponding to the eigenvalue $\lambda$. 

### Section : Using NumPy's linalg Module For Direct Computation

The 'linalg' module provides functions that can directly compute eigenvalues and their corresponding eigenvectors of a matrix ('ndarray' object).

In [2]:
A = np.array([[2, 0, 0], [1, 1, 2], [1, -1, 4]])

print(A)


[[ 2  0  0]
 [ 1  1  2]
 [ 1 -1  4]]


In [4]:
eig_val, eig_vec = LA.eig(A)

In [12]:
np.set_printoptions(precision=4)
for val_1, val_2 in zip(eig_val, eig_vec):
    print(f"Eigenvalue = {val_1} and Eigenvector: \n {val_2.reshape(-1, 1)}")

Eigenvalue = 3.0 and Eigenvector: 
 [[0.    ]
 [0.    ]
 [0.5774]]
Eigenvalue = 2.0 and Eigenvector: 
 [[ 0.7071]
 [ 0.8944]
 [-0.5774]]
Eigenvalue = 2.0 and Eigenvector: 
 [[ 0.7071]
 [ 0.4472]
 [-0.5774]]


In [16]:
# To get a more compact visualiztion of the values

from math import sqrt

print(round(1/sqrt(3), ndigits=4))
print(round(1/sqrt(2), ndigits=4))

0.5774
0.7071


In [23]:
# SymPy can be used to get equivalent results as given
# by Maple
from sympy import Matrix

A = Matrix(3, 3, [2, 0, 0, 1, 1, 2, 1, -1, 4])
print(A)
print()
print(A.eigenvals())
print()
print(A.eigenvects())

Matrix([[2, 0, 0], [1, 1, 2], [1, -1, 4]])

{2: 2, 3: 1}

[(2, 2, [Matrix([
[1],
[1],
[0]]), Matrix([
[-2],
[ 0],
[ 1]])]), (3, 1, [Matrix([
[0],
[1],
[1]])])]


### Section : l2 norm of A

The formula for computing the l2 norm is given by,

$||A||_{2} = \sqrt{\rho(A^{t}A)}$

In [30]:
A = np.array([[1, 1, 0], [1, 2, 1], [-1, 1, 2]])
print(A)


[[ 1  1  0]
 [ 1  2  1]
 [-1  1  2]]


In [31]:
At_A = np.matmul(np.transpose(A), A)
print(At_A)

[[ 3  2 -1]
 [ 2  6  4]
 [-1  4  5]]


In [35]:
l2_norm_A = round(np.sqrt(np.max(LA.eigvals(At_A))), ndigits=3)

print(f"The l2 norm of A is : {l2_norm_A}")


The l2 norm of A is : 3.106


In [37]:
# Directly Using NumPy
print(round(LA.norm(A, ord=2), ndigits=3))


3.106
