### Topic : Solving Systems of Linear Equations

In [40]:
# NumPy can be used to solve Systems of Linear Equations directly
import numpy as np
from numpy import linalg as LA
from typing import Optional

A = np.array([[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]], dtype=np.float64)
b = np.array([6, 25, -11, 15], dtype=np.float64)

LA.solve(A, b)

array([ 1.,  2., -1.,  1.])

### Section : Jacobi's Iterative Method

The __Jacobi iterative method__ is obtained by solving the ith equation in $A\bold{x} = \bold{b}$ for $x_{i}$ to obtain (provided $a_{ii} \ne 0$),

$$
x_{i} = \sum_{j = 1, j \ne i}^{n}(-\frac{a_{ij} x_{j}}{a_{ii}}) + \frac{b_{i}}{a_{ii}}
$$

For each $k \ge 1$, generate the components $x_{i}^{(k)}$ of $\bold{x^{(k)}}$ from components for $\bold{x}^{(k-1)}$ by,

$$
x_{i}^{(k)} = \frac{1}{a_{ii}} [\sum_{j = 1, j \ne i}^{n}(-a_{ij}x_{j}^{(k-1)}) + b_{i}] \quad for \quad i = 1, 2, 3,...., n
$$

In [87]:
def jacobi_iterative(
        coef_mat: np.ndarray,
        const_vec: np.ndarray,
        int_sol: np.ndarray) -> np.ndarray:

    temp_sol = np.zeros(coef_mat.shape[0],)

    for iteration in range(10):
        print(f"Iteration {iteration}: {int_sol}")
        for i in range(coef_mat.shape[0]):
            temp = 0.0
            for j in range(coef_mat.shape[1]):
                if j != i:
                    temp = temp - coef_mat[i, j] * int_sol[j]
            temp_sol[i] = (temp + const_vec[i]) / coef_mat[i, i]
        int_sol[:] = temp_sol[:]
    
    return int_sol

In [92]:
A = np.array([[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]], dtype=np.float64)
b = np.array([6, 25, -11, 15], dtype=np.float64)
x_0 = np.array([0, 0, 0 ,0], dtype=np.float64)

jacobi_iterative(A, b, x_0)

Iteration 0: [0. 0. 0. 0.]
Iteration 1: [ 0.6         2.27272727 -1.1         1.875     ]
Iteration 2: [ 1.04727273  1.71590909 -0.80522727  0.88522727]
Iteration 3: [ 0.93263636  2.05330579 -1.04934091  1.13088068]
Iteration 4: [ 1.01519876  1.95369576 -0.96810863  0.97384272]
Iteration 5: [ 0.9889913   2.01141473 -1.0102859   1.02135051]
Iteration 6: [ 1.00319865  1.99224126 -0.99452174  0.99443374]
Iteration 7: [ 0.99812847  2.00230688 -1.00197223  1.00359431]
Iteration 8: [ 1.00062513  1.9986703  -0.99903558  0.99888839]
Iteration 9: [ 0.99967415  2.00044767 -1.00036916  1.00061919]


array([ 1.0001186 ,  1.99976795, -0.99982814,  0.99978598])

### Topic: Gauss-Seidel Iterative Method

In [ ]:
def gauss_seidel_iterative(
        coef_mat: np.ndarray,
        const_vec: np.ndarray,
        int_sol: np.ndarray) -> np.ndarray:

    for iteration in range(10):
        print(f"Iteration {iteration}: {int_sol}")
        for i in range(coef_mat.shape[0]):
            temp = 0.0
            for j in range(coef_mat.shape[1]):
                if j != i:
                    temp = temp - coef_mat[i, j] * int_sol[j]
            int_sol[i] = (temp + const_vec[i]) / coef_mat[i, i]
    
    return int_sol

In [93]:
A = np.array([[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]], dtype=np.float64)
b = np.array([6, 25, -11, 15], dtype=np.float64)
x_0 = np.array([0, 0, 0 ,0], dtype=np.float64)

gauss_seidel_iterative(A, b, x_0)

Iteration 0: [0. 0. 0. 0.]
Iteration 1: [ 0.6         2.32727273 -0.98727273  0.87886364]
Iteration 2: [ 1.03018182  2.03693802 -1.0144562   0.98434122]
Iteration 3: [ 1.00658504  2.00355502 -1.00252738  0.99835095]
Iteration 4: [ 1.00086098  2.00029825 -1.00030728  0.99984975]
Iteration 5: [ 1.00009128  2.00002134 -1.00003115  0.9999881 ]
Iteration 6: [ 1.00000836  2.00000117 -1.00000275  0.99999922]
Iteration 7: [ 1.00000067  2.00000002 -1.00000021  0.99999996]
Iteration 8: [ 1.00000004  1.99999999 -1.00000001  1.        ]
Iteration 9: [ 1.  2. -1.  1.]


array([ 1.,  2., -1.,  1.])