In [1]:
import numpy as np
from numpy import linalg as LA

### Section : Matrix Norm

In [2]:
A = np.array([[1, 2, -1], [0, 3, -1], [5, -1, 1]])
print(A)

[[ 1  2 -1]
 [ 0  3 -1]
 [ 5 -1  1]]


In [3]:
# Algorithm for computing l_inf of a matrix

def mat_inf_norm(mat_1: np.ndarray) -> float:
    # Initialize a 1-D array with equal number
    # of elements as the dimension of the nxn square matrix

    temp_vec = np.zeros(shape=(mat_1.shape[0],), dtype=np.float64)

    for index, row in enumerate(mat_1):
        temp_vec[index] = np.sum(np.abs(row))
    
    return np.max(temp_vec)

In [4]:
mat_inf_norm(A)

7.0

### Section : Using NumPy

In [8]:
mat_norm_inf_val = LA.norm(A, ord=np.inf)

print(mat_norm_inf_val)

7.0
