NumPy is huge and complex third-party library that is mainly used for high performance numerical computations in python. The core object of the numpy library is 'ndarray'. As we learn to use numpy, one of our main goals will be to become familiar with the 'ndarray' class and how NumPy leverages this class to enable high performance computing in python. We will see that most of the 'Global' functions offered through NumPy usually interacts with the 'ndarray' class. Anyone using Python for mathematical or scientific computations will eventually move on to using NumPy and another library built upon NumPy, called SciPy. We will slowly learn why that is the case from both implementation and hardware based perspective.

One of the important things to keep in mind before we start, is that NumPy is a massive library that offers vast amounts of functionalities. Almost always, we will not be interested in learning everything a library can offer, instead we will want to familiarize ourselves with the basics and try to attain a workable level of understanding of the functionalities that are available. 

I had an opportunity to learn from a French Lead Machine Learning Engineer working for a company that exclusively develops complex Artificial Intelligence applications. I think this is a good place to directly quote one of the important lessons he taught me : 'When it comes to libraries, it is often more important to know WHAT we can do with them, instead of knowing HOW we can use them.'

With that in mind, we will never even try to consciously memorize anything from a library. Instead we will try to learn how to read the detailed documentations provided by the creators of the respective libraries.

Although I have added the reference manual in this repository, I personally prefer using the official sites search bar to look for specific information.  

### Section 1 : Creating ndarray objects

In [2]:
import numpy as np

__Explicit Array Creation Syntax__

In [41]:
l = [1, 2, 3, 4, 5, 6]
print(type(l))

a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(f"Dimension of a: {a.ndim}")
print(type(a))

<class 'list'>
[1 2 3 4 5 6]
Dimension of a: 1
<class 'numpy.ndarray'>


In [40]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.array([[[1, 2], [2, 3]], [[2, 3], [3,4]]])
print(a)
print(f"Dimension of a: {a.ndim}")
print(b)
print(f"Dimension of b: {b.ndim}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimension of a: 2
[[[1 2]
  [2 3]]

 [[2 3]
  [3 4]]]
Dimension of b: 3


__Array Initializers__

__np.zeros__

This method can be used to initialize an array with all zero elements.

Parameters:

1. shape : This parameter can be used to define the shape and dimension of the initialized array

2. dtype : This parameter can be used to initialize an array with a specified datatype such as np.int32, np.int64, np.float32, np.float64 etc


In [5]:
a = np.zeros(shape=(3, 3), dtype=np.int64)
b = np.zeros(shape=(2, 2), dtype=np.float64)
print(a)
print()
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[0. 0.]
 [0. 0.]]


__np.ones__

This method can be used to initialize an array with all elements set to one.

Parameters:

1. shape : This parameter can be used to define the shape and dimension of the initialized array

2. dtype : This parameter can be used to initialize an array with a specified datatype such as np.int32, np.int64, np.float32, np.float64 etc

In [6]:
a = np.ones(shape=(3, 3), dtype=np.int64)
b = np.ones(shape=(2, 2), dtype=np.float64)
print(a)
print()
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[1. 1.]
 [1. 1.]]


__np.empty__

This method can be used to initialize an array with all elements set to 'garbage'(values that are currently stored in memory) values. 

Parameters:

1. shape : This parameter can be used to define the shape and dimension of the initialized array

2. dtype : This parameter can be used to initialize an array with a specified datatype such as np.int32, np.int64, np.float32, np.float64 etc

In [7]:
a_empty = np.empty(shape=(3, 3), dtype=np.int64)
b_empty = np.empty(shape=(2, 2), dtype=np.float64)
print(a_empty)
print()
print(b_empty)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[1. 1.]
 [1. 1.]]


__Array Creators__

__np.arange__

https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy-arange

Return evenly spaced values within a given interval.

Parameters:

1. start : integer or real, optional

    Start of interval. The interval includes this value. The default start value is 0.

2. stop : integer or real

    End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

3. step : integer or real, optional

    Spacing between values.

2. dtype : This parameter can be used to initialize an array with a specified datatype such as np.int32, np.int64, np.float32, np.float64 etc

In [8]:
a = np.arange(start=0, stop=11, dtype=np.int64)
print(a)
print()
b = np.arange(start=0, stop=11, step=2, dtype=np.int64)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]

[ 0  2  4  6  8 10]


__np.linspace__

https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy-linspace

This method can be used to create an array with values that are spaced linearly in a specified interval.

In [12]:
# np.set_printoptions lets us define floating point value precision
# or how many values to print after decimal
np.set_printoptions(precision=4)

N = 8
x1 = np.linspace(start=0, stop=10, num=N, endpoint=True)
x2 = np.linspace(start=0, stop=10, num=N, endpoint=False)

# By default endpoint is set to True
x3 = np.linspace(start=0, stop=10, num=N)

print(x1)
print(x2)
print(x3)

[ 0.      1.4286  2.8571  4.2857  5.7143  7.1429  8.5714 10.    ]
[0.   1.25 2.5  3.75 5.   6.25 7.5  8.75]
[ 0.      1.4286  2.8571  4.2857  5.7143  7.1429  8.5714 10.    ]


### Section 2 : ndarray Object Attributes

Another way to create ndarray objects is to use a PRNG, to initialize all values randomly.

PRNG(Psuedo Random Number Generator) are used to generate sequences that seem to be random but are not 'truly' random as they are generated by using deterministic algorithms.

In [20]:
prng = np.random.default_rng(seed=1)
print(f"PRNG used: {prng}\n")

A = prng.random((3,3))
print(A)
print()
print(type(A))

# Only to ensure that the output shows up on github
print(str(type(A)).replace("<","").replace(">",""))

PRNG used: Generator(PCG64)

[[0.5118 0.9505 0.1442]
 [0.9486 0.3118 0.4233]
 [0.8277 0.4092 0.5496]]

<class 'numpy.ndarray'>
class 'numpy.ndarray'


__Attributes/Properties of a ndarray object:__

__ndim:__ Returns the Euclidean dimension (n of $R^{n}$) of an ndarray

__size:__ Returns total elements of an ndarray

__shape:__ Returns the dimensions of an ndarray

In [31]:
print(f"ndarray object A is: \n\n {A}\n")
print(f"Euclidean Dimension of A is: {A.ndim}\n")
print(f"Total number of elements in A is: {A.size}\n")
print(f"The dimensions of A are: {A.shape}")

ndarray object A is: 

 [[0.5118 0.9505 0.1442]
 [0.9486 0.3118 0.4233]
 [0.8277 0.4092 0.5496]]

Euclidean Dimension of A is: 2

Total number of elements in A is: 9

The dimensions of A are: (3, 3)
